### ISSUE TITLE
.haml(/* json */) doesn't seem to be working in recent commits

### ISSUE THREAD

**Issue by bryanwb** [creationix/jquery-haml#1]
First off, I really like this project and hope to use in production for the Karma Project http://karmaeducation.org

Unfortunately, none of the recent commits work for me

  $(document).ready(function(){
  $('#knavbar').haml(["%p", "hello world"]);

  });

Nothing happens when I run this code. No errors even. nothing.

I am using this client-side w/ out a server-side. Maybe the changes you made to make it work server-side broke it on client-side?

I had to go back 3 commits from head to find a version that works for me
83dc710a1149572cf3d3ea4ac855a93e86ca7686

I am testing on Firefox 3.5 and the latest Chromium on linux and w/ jquery 1.3.2

I hope u keep working on this, it is extremely useful to me. tks again

**Comment by creationix** [comment]
I'm having trouble reproducing your issue, could you point me to a page with the broken code or send a zip with the files.

Also, as a jQuery hint, the following should work too:

```
$(function () {
  $('#knavbar').haml(["%p", "hello world"]);
});
```

When you pass a function to the jquery function it treats it as an onload.  It's a nice shortcut

**Comment by creationix** [comment]
Also make sure that $ is jQuery in your scope.  If you are including Prototype also it will override jQuery's shortcut.  

I just updated the docs, they should be correct now.  The example included is tested working.

**Comment by creationix** [comment]
It appears to be working now, let me know if you have any more problems.
