### ISSUE TITLE
Parse error in Safari

### ISSUE THREAD

**Issue by tomtaylor** [creationix/jquery-haml#2]
Safari 4.0.4 seems to choke on the following JS, which works fine in Firefox:

```
var liElement = ["%li", { class : "picture", id : "picture-" + pictureId },
  ["%img", { src: "/newspapers/1/pictures/" + pictureId + ".jpg?size=card"}],
  [".actions", 
    ["%p.small", 
      ["%a", { href: "#", class : 'button tight place-picture' }, "Place"],
      ["%br"],
      ["%a", { href: "/newspapers/1/pictures/" + pictureId + "/delete", class : 'button tight red' }, "Delete"]
    ]
  ]
];

$('ul.pictures').haml(liElement);
```

**Comment by creationix** [comment]
I can't reproduce any errors.  What version of Safari are you on.

BTW, if you get a parse error it's the browser complaining about your JSON.  There is nothing my library can do about it.  My initial guess was that Safari was complaining about your key of "class".  Technically JSON keys are required to always have double-quotes around them.  It's JavaScript parsers that are more lax about it.

**Comment by tomtaylor** [comment]
Sorry for not following this up sooner - of course, you're right. Safari is a bit stricter at parsing JS than Firefox. I wrapped class in quotes, and it works fine. Sorry again!

**Comment by creationix** [comment]
No problem, I'm here to help.  I'm just glad people are using my library.
