### ISSUE TITLE
render haml and return it?

### ISSUE THREAD

**Issue by jsmestad** [creationix/jquery-haml#4]
is there a function to just do something like

```
var stupid = $.haml(["div", "Hey man"])
// would return "<div>Hey man</div>"
```

?

**Comment by creationix** [comment]
Not in jquery-haml, it's a dom-building library (Technically you could get the innerHTML of the created elements, but that would be silly.

I have another library that does just that.  It's called haml-js.  It should run in the browser or on server-side js.
