### ISSUE TITLE
How to do JSON object interpolation?

### ISSUE THREAD

**Issue by makuchaku** [creationix/jquery-haml#5]
Hi,

I have a JSON object
<code>var data = {'name' : 'bar', 'email' : 'bar'}</code>

and javascript that executes like
<code>$('#puncture-header-name').html("Hi, " + data.name + " (" + data.email + ")").show();  // non haml version</code>

Then how can I interpolate my data.name, etc variables so that I can use jquery-haml?

Thanks :)

**Comment by creationix** [comment]
You can just concat your strings and insert them as a text node in the json.  Also you can use the $ extension and call .html on the new node just like you just did.

**Comment by makuchaku** [comment]
Thanks - got the point :)
Is there any way to do interpolation? Using ""+"" is very cumbersome..

**Comment by creationix** [comment]
I don't think so, but it shouldn't be hard to add if you want to send a patch.

"Hello, @data.name (@data.email)"?

**Comment by creationix** [comment]
or "Hello, {data.name} ({data.email})"

**Comment by makuchaku** [comment]
I'm not sure that I have such good javascript skills, but let me try :)
Thanks!
